### ISSUE TITLE
ninja installation

### ISSUE THREAD

**Issue by dglazier** [gavalian/hipo#69]
I have reinstalled hipo4 with ninja. This works fine for clas12root. However when I go on to try and install with iguana it is not finding hipo4. I have tried running the environment scripts as suggested in the hipo docs to see if that fixes it, but get an error that the bin dir is not found,
   
      source install/libexec/this_hipo.sh
      bash: cd: /home/dglazier/Dropbox/clas12/gagik/hipo/install/lib/pkgconfig/../../bin: No such file or directory

Any obvious fixes for this ?

**Comment by c-dilks** [comment]
Thanks for reporting! #70 will fix this.

In the meantime, you could set your environment manually:

| variable             | value                                                     |
| ---                  | ---                                                       |
| `$PKG_CONFIG_PATH`   | `$prefix/lib/pkgconfig`                                   |
| `$LD_LIBRARY_PATH`   | `$prefix/lib`                                             |
| `$ROOT_INCLUDE_PATH` | `$prefix/include`                                         |
| `$PATH`              | `$prefix/bin` (only you installed executables (unlikely)) |

where `$prefix` is your HIPO installation path.

This won't be an issue on `ifarm`, since the Environment Modules takes care of this.
